"""Curated asset catalog — verified free game assets from itch.io, GitHub, and OpenGameArt.

Each entry has a verified download URL, license, preview, and tags.
This is intentionally curated (not scraped) for quality control.
"""

CATALOG = {
    "categories": [
        {"id": "tilesets", "name": "Tilesets", "icon": "🗺️"},
        {"id": "characters", "name": "Characters & Sprites", "icon": "🧙"},
        {"id": "ui", "name": "UI & HUD", "icon": "🖥️"},
        {"id": "fx", "name": "Effects & Particles", "icon": "✨"},
        {"id": "audio", "name": "Music & SFX", "icon": "🎵"},
        {"id": "templates", "name": "Game Templates", "icon": "🎮"},
        {"id": "tools", "name": "Tools & Addons", "icon": "🔧"},
        {"id": "3d", "name": "3D Models", "icon": "📦"},
    ],
    "assets": [
        # --- TILESETS ---
        {
            "id": "dungeon-tileset-ii",
            "name": "Dungeon Tileset II",
            "author": "0x72",
            "source": "itch.io",
            "url": "https://0x72.itch.io/dungeontileset-ii",
            "download_url": "https://0x72.itch.io/dungeontileset-ii",
            "license": "CC0",
            "category": "tilesets",
            "tags": ["pixel-art", "dungeon", "rpg", "16x16", "fantasy"],
            "description": "Free 16x16 dungeon tileset with characters, items, and environment tiles. One of the most popular free game asset packs.",
            "preview": "https://img.itch.zone/aW1nLzEyMDQ0MTIucG5n/315x250%23c/VqJF9W.png",
        },
        {
            "id": "16x16-rpg-tileset",
            "name": "16x16 DungeonTileset",
            "author": "0x72",
            "source": "itch.io",
            "url": "https://0x72.itch.io/16x16-dungeon-tileset",
            "download_url": "https://0x72.itch.io/16x16-dungeon-tileset",
            "license": "CC0",
            "category": "tilesets",
            "tags": ["pixel-art", "dungeon", "rpg", "16x16"],
            "description": "Original 16x16 dungeon tileset — walls, floors, doors, chests, characters.",
            "preview": "https://img.itch.zone/aW1nLzExNzA3MTMucG5n/315x250%23c/XTy3YD.png",
        },
        {
            "id": "pixel-platformer",
            "name": "Pixel Adventure",
            "author": "Pixel Frog",
            "source": "itch.io",
            "url": "https://pixelfrog-assets.itch.io/pixel-adventure-1",
            "download_url": "https://pixelfrog-assets.itch.io/pixel-adventure-1",
            "license": "Free",
            "category": "tilesets",
            "tags": ["pixel-art", "platformer", "animated", "32x32"],
            "description": "Complete platformer asset pack with animated characters, enemies, traps, items, and tilesets.",
            "preview": "https://img.itch.zone/aW1nLzI2NjA0NDEucG5n/315x250%23c/GBxNI9.png",
        },
        {
            "id": "nature-tileset",
            "name": "Tiny RPG - Forest Tileset",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/tiny-dungeon",
            "download_url": "https://kenney.nl/media/pages/assets/tiny-dungeon/3fa5f9c7ab-1696742968/kenney_tiny-dungeon.zip",
            "license": "CC0",
            "category": "tilesets",
            "tags": ["pixel-art", "rpg", "dungeon", "16x16"],
            "description": "Tiny 16x16 dungeon tileset from Kenney — 100% free, CC0 license.",
            "preview": "https://kenney.nl/media/pages/assets/tiny-dungeon/3fa5f9c7ab-1696742968/preview.png",
        },
        {
            "id": "modern-interiors",
            "name": "Modern Interiors",
            "author": "LimeZu",
            "source": "itch.io",
            "url": "https://limezu.itch.io/moderninteriors",
            "download_url": "https://limezu.itch.io/moderninteriors",
            "license": "Free",
            "category": "tilesets",
            "tags": ["pixel-art", "modern", "interior", "rpg", "16x16"],
            "description": "Modern interior tileset with furniture, appliances, characters. Perfect for contemporary RPGs.",
            "preview": "https://img.itch.zone/aW1nLzQzMTMyNDkucG5n/315x250%23c/Fh1QJb.png",
        },

        # --- CHARACTERS & SPRITES ---
        {
            "id": "ninja-adventure",
            "name": "Ninja Adventure Asset Pack",
            "author": "Pixel-Boy & AAA",
            "source": "itch.io",
            "url": "https://pixel-boy.itch.io/ninja-adventure-asset-pack",
            "download_url": "https://pixel-boy.itch.io/ninja-adventure-asset-pack",
            "license": "CC0",
            "category": "characters",
            "tags": ["pixel-art", "rpg", "characters", "enemies", "tilesets", "16x16"],
            "description": "Massive CC0 asset pack: 20+ characters, 100+ enemies, tilesets, items, GUI, music. Everything you need for an RPG.",
            "preview": "https://img.itch.zone/aW1nLzI2OTcyOTUucG5n/315x250%23c/3DWjnl.png",
        },
        {
            "id": "animated-pixel-adventurer",
            "name": "Animated Pixel Adventurer",
            "author": "rvros",
            "source": "itch.io",
            "url": "https://rvros.itch.io/animated-pixel-hero",
            "download_url": "https://rvros.itch.io/animated-pixel-hero",
            "license": "Free",
            "category": "characters",
            "tags": ["pixel-art", "animated", "character", "platformer", "32x32"],
            "description": "Animated pixel art adventurer with run, jump, attack, death animations.",
            "preview": "https://img.itch.zone/aW1nLzE1NjQ0NjkucG5n/315x250%23c/pFPwfs.png",
        },
        {
            "id": "kenney-characters",
            "name": "Kenney 1-Bit Pack",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/1-bit-pack",
            "download_url": "https://kenney.nl/media/pages/assets/1-bit-pack/786c14f1ab-1696742811/kenney_1-bit-pack.zip",
            "license": "CC0",
            "category": "characters",
            "tags": ["pixel-art", "1-bit", "characters", "items", "monochrome"],
            "description": "1000+ 1-bit sprites — characters, items, UI, environment. CC0.",
            "preview": "https://kenney.nl/media/pages/assets/1-bit-pack/786c14f1ab-1696742811/preview.png",
        },

        # --- UI & HUD ---
        {
            "id": "kenney-ui",
            "name": "Kenney UI Pack",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/ui-pack",
            "download_url": "https://kenney.nl/media/pages/assets/ui-pack/20d157f67f-1696743165/kenney_ui-pack.zip",
            "license": "CC0",
            "category": "ui",
            "tags": ["ui", "hud", "buttons", "panels", "icons"],
            "description": "Complete UI pack: buttons, panels, sliders, checkboxes, icons. CC0.",
            "preview": "https://kenney.nl/media/pages/assets/ui-pack/20d157f67f-1696743165/preview.png",
        },
        {
            "id": "kenney-ui-rpg",
            "name": "Kenney UI Pack RPG Expansion",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/ui-pack-rpg-expansion",
            "download_url": "https://kenney.nl/media/pages/assets/ui-pack-rpg-expansion/a5c8d73e41-1696743166/kenney_ui-pack-rpg-expansion.zip",
            "license": "CC0",
            "category": "ui",
            "tags": ["ui", "rpg", "inventory", "health-bar", "mana-bar"],
            "description": "RPG UI expansion: health bars, mana bars, inventory slots, character frames.",
            "preview": "https://kenney.nl/media/pages/assets/ui-pack-rpg-expansion/a5c8d73e41-1696743166/preview.png",
        },

        # --- AUDIO ---
        {
            "id": "kenney-music-jingles",
            "name": "Kenney Music Jingles",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/music-jingles",
            "download_url": "https://kenney.nl/media/pages/assets/music-jingles/b46ee65d25-1696742983/kenney_music-jingles.zip",
            "license": "CC0",
            "category": "audio",
            "tags": ["music", "jingles", "sfx", "ogg"],
            "description": "Short music jingles for game events — win, lose, level up, etc. CC0.",
            "preview": "",
        },
        {
            "id": "shapeforms-sfx",
            "name": "Shapeforms Audio Free SFX",
            "author": "Shapeforms",
            "source": "itch.io",
            "url": "https://shapeforms.itch.io/shapeforms-audio-free-sfx",
            "download_url": "https://shapeforms.itch.io/shapeforms-audio-free-sfx",
            "license": "Free",
            "category": "audio",
            "tags": ["sfx", "sound-effects", "sci-fi", "fantasy"],
            "description": "200+ free sound effects — hits, explosions, UI, sci-fi, fantasy.",
            "preview": "https://img.itch.zone/aW1nLzMzOTI4NjkucG5n/315x250%23c/2qvBdP.png",
        },

        # --- GAME TEMPLATES (GitHub) ---
        {
            "id": "maaack-game-template",
            "name": "Maaack's Godot Game Template",
            "author": "Maaack",
            "source": "github",
            "url": "https://github.com/Maaack/Godot-Game-Template",
            "download_url": "https://github.com/Maaack/Godot-Game-Template/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "templates",
            "tags": ["template", "menus", "options", "pause", "save-load", "godot-4"],
            "description": "Complete game template: main menu, options, pause, credits, scene loader, save/load. Best base for any Godot game.",
            "preview": "https://raw.githubusercontent.com/Maaack/Godot-Game-Template/main/addons/maaacks_game_template/media/images/Screenshot-3-Title.png",
        },
        {
            "id": "godot-open-rpg",
            "name": "Godot Open RPG",
            "author": "food-please (GDQuest fork)",
            "source": "github",
            "url": "https://github.com/food-please/godot4-open-rpg",
            "download_url": "https://github.com/food-please/godot4-open-rpg/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "templates",
            "tags": ["rpg", "turn-based", "combat", "inventory", "dialogue", "godot-4"],
            "description": "Complete turn-based RPG template: combat system, inventory, dialogue, grid movement, character progression.",
            "preview": "",
        },
        {
            "id": "godot-gamejam",
            "name": "Game Jam Template",
            "author": "bitbrain",
            "source": "github",
            "url": "https://github.com/bitbrain/godot-gamejam",
            "download_url": "https://github.com/bitbrain/godot-gamejam/archive/refs/heads/godot-4.x.zip",
            "license": "MIT",
            "category": "templates",
            "tags": ["template", "game-jam", "quick-start", "2d", "3d", "godot-4"],
            "description": "Quick-start template for game jams. Minimal boilerplate, 2D/3D ready.",
            "preview": "",
        },
        {
            "id": "2d-platformer-starter",
            "name": "2D Platformer Starter Kit",
            "author": "brettchalupa",
            "source": "github",
            "url": "https://github.com/brettchalupa/godot_2d_platformer",
            "download_url": "https://github.com/brettchalupa/godot_2d_platformer/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "templates",
            "tags": ["platformer", "2d", "starter-kit", "levels", "enemies", "godot-4"],
            "description": "Complete 2D platformer with player controller, enemies, levels, and collectibles.",
            "preview": "",
        },

        # --- TOOLS & ADDONS ---
        {
            "id": "gd-dialog",
            "name": "GD Dialog System",
            "author": "QueenChristina",
            "source": "github",
            "url": "https://github.com/QueenChristina/gd_dialog",
            "download_url": "https://github.com/QueenChristina/gd_dialog/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "tools",
            "tags": ["dialogue", "rpg", "visual-novel", "json", "addon"],
            "description": "JSON-driven dialogue system for RPGs, visual novels, and adventure games.",
            "preview": "",
        },
        {
            "id": "building-system",
            "name": "Building System Starter Kit",
            "author": "MarkoDM",
            "source": "github",
            "url": "https://github.com/MarkoDM/GodotInGameBuildingSystem",
            "download_url": "https://github.com/MarkoDM/GodotInGameBuildingSystem/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "tools",
            "tags": ["building", "simulation", "grid", "freeform", "godot-4"],
            "description": "Grid-based and freeform building system for simulation and survival games.",
            "preview": "",
        },

        # --- 3D ---
        {
            "id": "kenney-nature-kit",
            "name": "Kenney Nature Kit",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/nature-kit",
            "download_url": "https://kenney.nl/media/pages/assets/nature-kit/87ea2c73cc-1696742989/kenney_nature-kit.zip",
            "license": "CC0",
            "category": "3d",
            "tags": ["3d", "nature", "trees", "rocks", "low-poly", "glb"],
            "description": "Low-poly 3D nature assets: trees, rocks, plants, fences. CC0.",
            "preview": "https://kenney.nl/media/pages/assets/nature-kit/87ea2c73cc-1696742989/preview.png",
        },
    ],
}


def get_catalog():
    return CATALOG

def search_catalog(query: str = "", category: str = "", tags: list = None):
    results = CATALOG["assets"]
    if category:
        results = [a for a in results if a["category"] == category]
    if query:
        q = query.lower()
        results = [a for a in results if q in a["name"].lower() or q in a["description"].lower() or any(q in t for t in a["tags"])]
    if tags:
        results = [a for a in results if any(t in a["tags"] for t in tags)]
    return results
