"""Curated asset catalog — verified free game assets from itch.io, GitHub, and OpenGameArt.

Each entry has a verified download URL, license, preview, and tags.
This is intentionally curated (not scraped) for quality control.
"""

CATALOG = {
    "categories": [
        {"id": "tilesets", "name": "Tilesets", "icon": "🗺️"},
        {"id": "characters", "name": "Characters & Sprites", "icon": "🧙"},
        {"id": "ui", "name": "UI & HUD", "icon": "🖥️"},
        {"id": "fx", "name": "Effects & Particles", "icon": "✨"},
        {"id": "audio", "name": "Music & SFX", "icon": "🎵"},
        {"id": "templates", "name": "Game Templates", "icon": "🎮"},
        {"id": "tools", "name": "Tools & Addons", "icon": "🔧"},
        {"id": "3d", "name": "3D Models", "icon": "📦"},
    ],
    "assets": [
        # --- TILESETS ---
        {
            "id": "dungeon-tileset-ii",
            "name": "Dungeon Tileset II",
            "author": "0x72",
            "source": "itch.io",
            "url": "https://0x72.itch.io/dungeontileset-ii",
            "download_url": "https://0x72.itch.io/dungeontileset-ii",
            "license": "CC0",
            "category": "tilesets",
            "tags": ["pixel-art", "dungeon", "rpg", "16x16", "fantasy"],
            "description": "Free 16x16 dungeon tileset with characters, items, and environment tiles. One of the most popular free game asset packs.",
            "preview": "https://img.itch.zone/aW1nLzEyMDQ0MTIucG5n/315x250%23c/VqJF9W.png",
        },
        {
            "id": "16x16-rpg-tileset",
            "name": "16x16 DungeonTileset",
            "author": "0x72",
            "source": "itch.io",
            "url": "https://0x72.itch.io/16x16-dungeon-tileset",
            "download_url": "https://0x72.itch.io/16x16-dungeon-tileset",
            "license": "CC0",
            "category": "tilesets",
            "tags": ["pixel-art", "dungeon", "rpg", "16x16"],
            "description": "Original 16x16 dungeon tileset — walls, floors, doors, chests, characters.",
            "preview": "https://img.itch.zone/aW1nLzExNzA3MTMucG5n/315x250%23c/XTy3YD.png",
        },
        {
            "id": "pixel-platformer",
            "name": "Pixel Adventure",
            "author": "Pixel Frog",
            "source": "itch.io",
            "url": "https://pixelfrog-assets.itch.io/pixel-adventure-1",
            "download_url": "https://pixelfrog-assets.itch.io/pixel-adventure-1",
            "license": "Free",
            "category": "tilesets",
            "tags": ["pixel-art", "platformer", "animated", "32x32"],
            "description": "Complete platformer asset pack with animated characters, enemies, traps, items, and tilesets.",
            "preview": "https://img.itch.zone/aW1nLzI2NjA0NDEucG5n/315x250%23c/GBxNI9.png",
        },
        {
            "id": "nature-tileset",
            "name": "Tiny RPG - Forest Tileset",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/tiny-dungeon",
            "download_url": "https://kenney.nl/media/pages/assets/tiny-dungeon/3fa5f9c7ab-1696742968/kenney_tiny-dungeon.zip",
            "license": "CC0",
            "category": "tilesets",
            "tags": ["pixel-art", "rpg", "dungeon", "16x16"],
            "description": "Tiny 16x16 dungeon tileset from Kenney — 100% free, CC0 license.",
            "preview": "https://kenney.nl/media/pages/assets/tiny-dungeon/3fa5f9c7ab-1696742968/preview.png",
        },
        {
            "id": "modern-interiors",
            "name": "Modern Interiors",
            "author": "LimeZu",
            "source": "itch.io",
            "url": "https://limezu.itch.io/moderninteriors",
            "download_url": "https://limezu.itch.io/moderninteriors",
            "license": "Free",
            "category": "tilesets",
            "tags": ["pixel-art", "modern", "interior", "rpg", "16x16"],
            "description": "Modern interior tileset with furniture, appliances, characters. Perfect for contemporary RPGs.",
            "preview": "https://img.itch.zone/aW1nLzQzMTMyNDkucG5n/315x250%23c/Fh1QJb.png",
        },

        # --- CHARACTERS & SPRITES ---
        {
            "id": "ninja-adventure",
            "name": "Ninja Adventure Asset Pack",
            "author": "Pixel-Boy & AAA",
            "source": "itch.io",
            "url": "https://pixel-boy.itch.io/ninja-adventure-asset-pack",
            "download_url": "https://pixel-boy.itch.io/ninja-adventure-asset-pack",
            "license": "CC0",
            "category": "characters",
            "tags": ["pixel-art", "rpg", "characters", "enemies", "tilesets", "16x16"],
            "description": "Massive CC0 asset pack: 20+ characters, 100+ enemies, tilesets, items, GUI, music. Everything you need for an RPG.",
            "preview": "https://img.itch.zone/aW1nLzI2OTcyOTUucG5n/315x250%23c/3DWjnl.png",
        },
        {
            "id": "animated-pixel-adventurer",
            "name": "Animated Pixel Adventurer",
            "author": "rvros",
            "source": "itch.io",
            "url": "https://rvros.itch.io/animated-pixel-hero",
            "download_url": "https://rvros.itch.io/animated-pixel-hero",
            "license": "Free",
            "category": "characters",
            "tags": ["pixel-art", "animated", "character", "platformer", "32x32"],
            "description": "Animated pixel art adventurer with run, jump, attack, death animations.",
            "preview": "https://img.itch.zone/aW1nLzE1NjQ0NjkucG5n/315x250%23c/pFPwfs.png",
        },
        {
            "id": "kenney-characters",
            "name": "Kenney 1-Bit Pack",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/1-bit-pack",
            "download_url": "https://kenney.nl/media/pages/assets/1-bit-pack/786c14f1ab-1696742811/kenney_1-bit-pack.zip",
            "license": "CC0",
            "category": "characters",
            "tags": ["pixel-art", "1-bit", "characters", "items", "monochrome"],
            "description": "1000+ 1-bit sprites — characters, items, UI, environment. CC0.",
            "preview": "https://kenney.nl/media/pages/assets/1-bit-pack/786c14f1ab-1696742811/preview.png",
        },

        # --- UI & HUD ---
        {
            "id": "kenney-ui",
            "name": "Kenney UI Pack",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/ui-pack",
            "download_url": "https://kenney.nl/media/pages/assets/ui-pack/20d157f67f-1696743165/kenney_ui-pack.zip",
            "license": "CC0",
            "category": "ui",
            "tags": ["ui", "hud", "buttons", "panels", "icons"],
            "description": "Complete UI pack: buttons, panels, sliders, checkboxes, icons. CC0.",
            "preview": "https://kenney.nl/media/pages/assets/ui-pack/20d157f67f-1696743165/preview.png",
        },
        {
            "id": "kenney-ui-rpg",
            "name": "Kenney UI Pack RPG Expansion",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/ui-pack-rpg-expansion",
            "download_url": "https://kenney.nl/media/pages/assets/ui-pack-rpg-expansion/a5c8d73e41-1696743166/kenney_ui-pack-rpg-expansion.zip",
            "license": "CC0",
            "category": "ui",
            "tags": ["ui", "rpg", "inventory", "health-bar", "mana-bar"],
            "description": "RPG UI expansion: health bars, mana bars, inventory slots, character frames.",
            "preview": "https://kenney.nl/media/pages/assets/ui-pack-rpg-expansion/a5c8d73e41-1696743166/preview.png",
        },

        # --- AUDIO ---
        {
            "id": "kenney-music-jingles",
            "name": "Kenney Music Jingles",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/music-jingles",
            "download_url": "https://kenney.nl/media/pages/assets/music-jingles/b46ee65d25-1696742983/kenney_music-jingles.zip",
            "license": "CC0",
            "category": "audio",
            "tags": ["music", "jingles", "sfx", "ogg"],
            "description": "Short music jingles for game events — win, lose, level up, etc. CC0.",
            "preview": "",
        },
        {
            "id": "shapeforms-sfx",
            "name": "Shapeforms Audio Free SFX",
            "author": "Shapeforms",
            "source": "itch.io",
            "url": "https://shapeforms.itch.io/shapeforms-audio-free-sfx",
            "download_url": "https://shapeforms.itch.io/shapeforms-audio-free-sfx",
            "license": "Free",
            "category": "audio",
            "tags": ["sfx", "sound-effects", "sci-fi", "fantasy"],
            "description": "200+ free sound effects — hits, explosions, UI, sci-fi, fantasy.",
            "preview": "https://img.itch.zone/aW1nLzMzOTI4NjkucG5n/315x250%23c/2qvBdP.png",
        },

        # --- GAME TEMPLATES (GitHub) ---
        {
            "id": "maaack-game-template",
            "name": "Maaack's Godot Game Template",
            "author": "Maaack",
            "source": "github",
            "url": "https://github.com/Maaack/Godot-Game-Template",
            "download_url": "https://github.com/Maaack/Godot-Game-Template/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "templates",
            "tags": ["template", "menus", "options", "pause", "save-load", "godot-4"],
            "description": "Complete game template: main menu, options, pause, credits, scene loader, save/load. Best base for any Godot game.",
            "preview": "https://raw.githubusercontent.com/Maaack/Godot-Game-Template/main/addons/maaacks_game_template/media/images/Screenshot-3-Title.png",
        },
        {
            "id": "godot-open-rpg",
            "name": "Godot Open RPG",
            "author": "food-please (GDQuest fork)",
            "source": "github",
            "url": "https://github.com/food-please/godot4-open-rpg",
            "download_url": "https://github.com/food-please/godot4-open-rpg/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "templates",
            "tags": ["rpg", "turn-based", "combat", "inventory", "dialogue", "godot-4"],
            "description": "Complete turn-based RPG template: combat system, inventory, dialogue, grid movement, character progression.",
            "preview": "",
        },
        {
            "id": "godot-gamejam",
            "name": "Game Jam Template",
            "author": "bitbrain",
            "source": "github",
            "url": "https://github.com/bitbrain/godot-gamejam",
            "download_url": "https://github.com/bitbrain/godot-gamejam/archive/refs/heads/godot-4.x.zip",
            "license": "MIT",
            "category": "templates",
            "tags": ["template", "game-jam", "quick-start", "2d", "3d", "godot-4"],
            "description": "Quick-start template for game jams. Minimal boilerplate, 2D/3D ready.",
            "preview": "",
        },
        {
            "id": "2d-platformer-starter",
            "name": "2D Platformer Starter Kit",
            "author": "brettchalupa",
            "source": "github",
            "url": "https://github.com/brettchalupa/godot_2d_platformer",
            "download_url": "https://github.com/brettchalupa/godot_2d_platformer/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "templates",
            "tags": ["platformer", "2d", "starter-kit", "levels", "enemies", "godot-4"],
            "description": "Complete 2D platformer with player controller, enemies, levels, and collectibles.",
            "preview": "",
        },

        # --- TOOLS & ADDONS ---
        {
            "id": "gd-dialog",
            "name": "GD Dialog System",
            "author": "QueenChristina",
            "source": "github",
            "url": "https://github.com/QueenChristina/gd_dialog",
            "download_url": "https://github.com/QueenChristina/gd_dialog/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "tools",
            "tags": ["dialogue", "rpg", "visual-novel", "json", "addon"],
            "description": "JSON-driven dialogue system for RPGs, visual novels, and adventure games.",
            "preview": "",
        },
        {
            "id": "building-system",
            "name": "Building System Starter Kit",
            "author": "MarkoDM",
            "source": "github",
            "url": "https://github.com/MarkoDM/GodotInGameBuildingSystem",
            "download_url": "https://github.com/MarkoDM/GodotInGameBuildingSystem/archive/refs/heads/main.zip",
            "license": "MIT",
            "category": "tools",
            "tags": ["building", "simulation", "grid", "freeform", "godot-4"],
            "description": "Grid-based and freeform building system for simulation and survival games.",
            "preview": "",
        },

        # --- 3D ---
        {
            "id": "kenney-nature-kit",
            "name": "Kenney Nature Kit",
            "author": "Kenney",
            "source": "kenney.nl",
            "url": "https://kenney.nl/assets/nature-kit",
            "download_url": "https://kenney.nl/media/pages/assets/nature-kit/87ea2c73cc-1696742989/kenney_nature-kit.zip",
            "license": "CC0",
            "category": "3d",
            "tags": ["3d", "nature", "trees", "rocks", "low-poly", "glb"],
            "description": "Low-poly 3D nature assets: trees, rocks, plants, fences. CC0.",
            "preview": "https://kenney.nl/media/pages/assets/nature-kit/87ea2c73cc-1696742989/preview.png",
        },
        # --- MORE KENNEY PACKS ---
        {
            "id": "kenney-platformer-art",
            "name": "Kenney Platformer Art (Pixel Redux)",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/platformer-art-pixel-redux",
            "download_url": "https://kenney.nl/media/pages/assets/platformer-art-pixel-redux/1b2bf03e68-1696743038/kenney_platformer-art-pixel-redux.zip",
            "license": "CC0", "category": "tilesets",
            "tags": ["pixel-art", "platformer", "tiles", "characters", "items"],
            "description": "Complete pixel platformer art: tiles, characters, enemies, items, backgrounds. Everything for a 2D platformer.",
            "preview": "",
        },
        {
            "id": "kenney-pixel-platformer",
            "name": "Kenney Pixel Platformer",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/pixel-platformer",
            "download_url": "https://kenney.nl/media/pages/assets/pixel-platformer/02f25619a5-1696743030/kenney_pixel-platformer.zip",
            "license": "CC0", "category": "tilesets",
            "tags": ["pixel-art", "platformer", "18x18", "characters", "tiles"],
            "description": "18x18 pixel platformer assets: terrain, props, characters, items.",
            "preview": "",
        },
        {
            "id": "kenney-tiny-town",
            "name": "Kenney Tiny Town",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/tiny-town",
            "download_url": "https://kenney.nl/media/pages/assets/tiny-town/5b4dab2dc5-1696743161/kenney_tiny-town.zip",
            "license": "CC0", "category": "tilesets",
            "tags": ["pixel-art", "rpg", "town", "buildings", "16x16"],
            "description": "16x16 town tileset: buildings, roads, trees, fences, characters.",
            "preview": "",
        },
        {
            "id": "kenney-animal-pack",
            "name": "Kenney Animal Pack Redux",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/animal-pack-redux",
            "download_url": "https://kenney.nl/media/pages/assets/animal-pack-redux/c4fbceac50-1696742815/kenney_animal-pack-redux.zip",
            "license": "CC0", "category": "characters",
            "tags": ["2d", "animals", "characters", "sprites"],
            "description": "Cute 2D animal sprites: bear, cat, dog, duck, elephant, fox, giraffe, and more.",
            "preview": "",
        },
        {
            "id": "kenney-space-shooter",
            "name": "Kenney Space Shooter Redux",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/space-shooter-redux",
            "download_url": "https://kenney.nl/media/pages/assets/space-shooter-redux/65c81aaff6-1696743100/kenney_space-shooter-redux.zip",
            "license": "CC0", "category": "characters",
            "tags": ["space", "shooter", "ships", "lasers", "asteroids"],
            "description": "Space shooter assets: ships, enemies, lasers, meteors, power-ups, backgrounds.",
            "preview": "",
        },
        {
            "id": "kenney-roguelike-chars",
            "name": "Kenney Roguelike Characters",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/roguelike-characters",
            "download_url": "https://kenney.nl/media/pages/assets/roguelike-characters/1f34e3a26e-1696743064/kenney_roguelike-characters.zip",
            "license": "CC0", "category": "characters",
            "tags": ["roguelike", "rpg", "characters", "16x16", "fantasy"],
            "description": "16x16 roguelike character sprites: warriors, mages, enemies, NPCs.",
            "preview": "",
        },
        {
            "id": "kenney-roguelike-modern",
            "name": "Kenney Roguelike Modern City",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/roguelike-modern-city",
            "download_url": "https://kenney.nl/media/pages/assets/roguelike-modern-city/8d3207bb3b-1696743068/kenney_roguelike-modern-city.zip",
            "license": "CC0", "category": "tilesets",
            "tags": ["roguelike", "modern", "city", "16x16", "urban"],
            "description": "Modern city roguelike tileset: buildings, cars, roads, interiors.",
            "preview": "",
        },
        {
            "id": "kenney-monochrome-rpg",
            "name": "Kenney Monochrome RPG",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/monochrome-rpg",
            "download_url": "https://kenney.nl/media/pages/assets/monochrome-rpg/ed92b9f0b6-1696742974/kenney_monochrome-rpg.zip",
            "license": "CC0", "category": "tilesets",
            "tags": ["rpg", "monochrome", "16x16", "fantasy", "dungeon"],
            "description": "Monochrome RPG tileset: dungeons, towns, characters, items. Classic Gameboy style.",
            "preview": "",
        },
        {
            "id": "kenney-impact-sounds",
            "name": "Kenney Impact Sounds",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/impact-sounds",
            "download_url": "https://kenney.nl/media/pages/assets/impact-sounds/c2e2bd48b5-1696742957/kenney_impact-sounds.zip",
            "license": "CC0", "category": "audio",
            "tags": ["sfx", "impact", "hit", "crash", "ogg"],
            "description": "60+ impact/hit sound effects: punches, kicks, crashes, thuds. CC0.",
            "preview": "",
        },
        {
            "id": "kenney-interface-sounds",
            "name": "Kenney Interface Sounds",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/interface-sounds",
            "download_url": "https://kenney.nl/media/pages/assets/interface-sounds/d6e3c18b92-1696742959/kenney_interface-sounds.zip",
            "license": "CC0", "category": "audio",
            "tags": ["sfx", "ui", "menu", "click", "confirm"],
            "description": "100+ UI sound effects: clicks, confirms, cancels, notifications. CC0.",
            "preview": "",
        },
        {
            "id": "kenney-rpg-audio",
            "name": "Kenney RPG Audio",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/rpg-audio",
            "download_url": "https://kenney.nl/media/pages/assets/rpg-audio/01c40cb2e4-1696743078/kenney_rpg-audio.zip",
            "license": "CC0", "category": "audio",
            "tags": ["sfx", "rpg", "sword", "magic", "footsteps"],
            "description": "RPG sound effects: sword swings, magic spells, footsteps, doors, chests. CC0.",
            "preview": "",
        },
        {
            "id": "kenney-3d-nature",
            "name": "Kenney Nature Kit",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/nature-kit",
            "download_url": "https://kenney.nl/media/pages/assets/nature-kit/87ea2c73cc-1696742989/kenney_nature-kit.zip",
            "license": "CC0", "category": "3d",
            "tags": ["3d", "nature", "trees", "rocks", "low-poly", "gltf"],
            "description": "Low-poly 3D nature: trees, rocks, plants, fences, flowers. GLTF format. CC0.",
            "preview": "",
        },
        {
            "id": "kenney-3d-dungeon",
            "name": "Kenney Modular Dungeon Kit",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/modular-dungeon-kit",
            "download_url": "https://kenney.nl/media/pages/assets/modular-dungeon-kit/bc8c9b2a10-1710707088/kenney_modular-dungeon-kit.zip",
            "license": "CC0", "category": "3d",
            "tags": ["3d", "dungeon", "modular", "rpg", "gltf"],
            "description": "Modular 3D dungeon pieces: walls, floors, doors, stairs, torches. Snap together. CC0.",
            "preview": "",
        },
        {
            "id": "kenney-3d-car",
            "name": "Kenney Car Kit",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/car-kit",
            "download_url": "https://kenney.nl/media/pages/assets/car-kit/c5a3c7f4c5-1705332053/kenney_car-kit.zip",
            "license": "CC0", "category": "3d",
            "tags": ["3d", "car", "vehicle", "racing", "roads", "gltf"],
            "description": "Low-poly 3D cars, trucks, roads, and track pieces for racing games. CC0.",
            "preview": "",
        },
        {
            "id": "kenney-3d-fantasy-town",
            "name": "Kenney Fantasy Town Kit",
            "author": "Kenney", "source": "kenney.nl",
            "url": "https://kenney.nl/assets/fantasy-town-kit",
            "download_url": "https://kenney.nl/media/pages/assets/fantasy-town-kit/2c8e83a610-1718893261/kenney_fantasy-town-kit.zip",
            "license": "CC0", "category": "3d",
            "tags": ["3d", "fantasy", "town", "buildings", "rpg", "gltf"],
            "description": "3D fantasy town: houses, shops, castles, walls, props. Build medieval towns. CC0.",
            "preview": "",
        },

        # --- OPENGAMEART / COMMUNITY ---
        {
            "id": "oga-lpc-base",
            "name": "LPC Base Character Sprites",
            "author": "OpenGameArt community",
            "source": "opengameart.org",
            "url": "https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-702702702",
            "download_url": "https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-702702702",
            "license": "CC-BY-SA 3.0 / GPL 3.0",
            "category": "characters",
            "tags": ["pixel-art", "rpg", "character", "animated", "walk-cycle", "LPC"],
            "description": "Liberated Pixel Cup character base sprites with full walk cycles, combat animations. The standard for open-source RPG characters. Huge community of compatible add-ons.",
            "preview": "",
        },
        {
            "id": "oga-lpc-terrain",
            "name": "LPC Terrain Tileset",
            "author": "OpenGameArt community",
            "source": "opengameart.org",
            "url": "https://opengameart.org/content/lpc-terrainrepack",
            "download_url": "https://opengameart.org/content/lpc-terrainrepack",
            "license": "CC-BY-SA 3.0 / GPL 3.0",
            "category": "tilesets",
            "tags": ["pixel-art", "rpg", "terrain", "grass", "water", "LPC", "32x32"],
            "description": "LPC terrain tileset: grass, dirt, water, sand, snow, paths. Seamless, 32x32. Compatible with all LPC assets.",
            "preview": "",
        },
    ],
}


def get_catalog():
    return CATALOG

def search_catalog(query: str = "", category: str = "", tags: list = None):
    results = CATALOG["assets"]
    if category:
        results = [a for a in results if a["category"] == category]
    if query:
        q = query.lower()
        results = [a for a in results if q in a["name"].lower() or q in a["description"].lower() or any(q in t for t in a["tags"])]
    if tags:
        results = [a for a in results if any(t in a["tags"] for t in tags)]
    return results
