"""Pixel Art Studio — Style presets, animation configs, tileset configs, palettes.

Modeled after RetroDiffusion's feature set but running 100% local via ComfyUI.
"""

# =============================================================================
# STYLE PRESETS — organized by tier (pro, fast, plus) like RetroDiffusion
# =============================================================================

PIXEL_STYLE_PRESETS = {
    # --- PRO tier: highest quality, most control ---
    "default": {
        "name": "Default",
        "tier": "pro",
        "icon": "🎯",
        "prompt_prefix": "pixel art, clean crisp pixels, high quality sprite,",
        "negative_extra": "blurry, anti-aliased, smooth gradient, photo, 3D render",
        "suggested_palette": "",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "fantasy_rpg": {
        "name": "Fantasy RPG",
        "tier": "pro",
        "icon": "⚔️",
        "prompt_prefix": "16-bit fantasy RPG pixel art, rich warm colors, medieval setting,",
        "negative_extra": "modern, sci-fi, realistic, photo",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "painterly": {
        "name": "Painterly",
        "tier": "pro",
        "icon": "🎨",
        "prompt_prefix": "painterly pixel art, soft brushstroke style, impressionist pixel art, textured,",
        "negative_extra": "sharp, clean, hard edges, flat colors",
        "suggested_palette": "endesga64",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 96,
    },
    "horror": {
        "name": "Horror",
        "tier": "pro",
        "icon": "👻",
        "prompt_prefix": "dark pixel art horror, eerie atmosphere, creepy, unsettling, desaturated,",
        "negative_extra": "bright, cheerful, cute, colorful, pastel",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "scifi": {
        "name": "Sci-Fi",
        "tier": "pro",
        "icon": "🚀",
        "prompt_prefix": "pixel art sci-fi, neon glow, futuristic technology, cyberpunk, holographic,",
        "negative_extra": "medieval, nature, organic, rustic, warm colors",
        "suggested_palette": "sweetie16",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "ui_panel": {
        "name": "UI Panel",
        "tier": "pro",
        "icon": "🖼️",
        "prompt_prefix": "pixel art game UI panel, interface frame, menu border, ornate window,",
        "negative_extra": "character, landscape, scene, creature",
        "suggested_palette": "endesga32",
        "suggested_lora": "item",
        "suggested_resolution": 128,
    },
    "isometric": {
        "name": "Isometric",
        "tier": "pro",
        "icon": "🏠",
        "prompt_prefix": "isometric pixel art, 3/4 top-down view, dimetric projection, game asset,",
        "negative_extra": "side view, flat 2D, top-down, first person",
        "suggested_palette": "endesga32",
        "suggested_lora": "building",
        "suggested_resolution": 128,
    },
    "topdown": {
        "name": "Top-Down",
        "tier": "pro",
        "icon": "👁️",
        "prompt_prefix": "top-down pixel art, overhead view, RPG map style, birds eye view,",
        "negative_extra": "side view, isometric, 3D, perspective",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "platformer": {
        "name": "Platformer",
        "tier": "pro",
        "icon": "🏃",
        "prompt_prefix": "side-scrolling pixel art, platform game style, side view, action game,",
        "negative_extra": "top-down, isometric, 3D, overhead",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "dungeon_map": {
        "name": "Dungeon Map",
        "tier": "pro",
        "icon": "🗺️",
        "prompt_prefix": "pixel art dungeon map, top-down dungeon tileset, dark stone corridors, torch-lit,",
        "negative_extra": "outdoor, bright, modern, sci-fi",
        "suggested_palette": "endesga32",
        "suggested_lora": "tileset",
        "suggested_resolution": 64,
    },
    "spritesheet": {
        "name": "Sprite Sheet",
        "tier": "pro",
        "icon": "📋",
        "prompt_prefix": "pixel art sprite sheet, multiple poses, character turnaround, game asset,",
        "negative_extra": "single image, landscape, background",
        "suggested_palette": "endesga32",
        "suggested_lora": "character",
        "suggested_resolution": 64,
    },
    "hexagonal_tiles": {
        "name": "Hexagonal Tiles",
        "tier": "pro",
        "icon": "⬡",
        "prompt_prefix": "pixel art hexagonal tile, hex grid game asset, strategy game terrain,",
        "negative_extra": "square, rectangular, character, portrait",
        "suggested_palette": "endesga32",
        "suggested_lora": "tileset",
        "suggested_resolution": 64,
    },
    "fps_weapon": {
        "name": "FPS Weapon",
        "tier": "pro",
        "icon": "🔫",
        "prompt_prefix": "pixel art first person weapon, FPS game gun sprite, held weapon view,",
        "negative_extra": "top-down, side view, character, landscape",
        "suggested_palette": "endesga32",
        "suggested_lora": "gun",
        "suggested_resolution": 128,
    },
    "inventory_items": {
        "name": "Inventory Items",
        "tier": "pro",
        "icon": "🎒",
        "prompt_prefix": "pixel art inventory item icon, game item sprite, RPG equipment, icon grid,",
        "negative_extra": "character, landscape, scene, large",
        "suggested_palette": "sweetie16",
        "suggested_lora": "item",
        "suggested_resolution": 32,
    },
    "typography": {
        "name": "Typography",
        "tier": "pro",
        "icon": "🔤",
        "prompt_prefix": "pixel art text, bitmap font style, retro game title, pixel typography,",
        "negative_extra": "smooth, vector, anti-aliased, photo",
        "suggested_palette": "pico8",
        "suggested_lora": "none",
        "suggested_resolution": 64,
    },

    # --- FAST tier: quickest generation, lower cost ---
    "retro": {
        "name": "Retro",
        "tier": "fast",
        "icon": "📺",
        "prompt_prefix": "retro pixel art, nostalgic, vintage game style, classic gaming,",
        "negative_extra": "modern, HD, detailed, realistic",
        "suggested_palette": "nes",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 32,
    },
    "simple": {
        "name": "Simple / Minimal",
        "tier": "fast",
        "icon": "⬜",
        "prompt_prefix": "simple pixel art, minimal detail, clean shapes, flat colors, low resolution,",
        "negative_extra": "detailed, complex, textured, noisy, gradient",
        "suggested_palette": "pico8",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 32,
    },
    "detailed": {
        "name": "Detailed / HD",
        "tier": "fast",
        "icon": "🔍",
        "prompt_prefix": "highly detailed pixel art, intricate, sub-pixel rendering, rich texture,",
        "negative_extra": "simple, flat, minimal, low resolution",
        "suggested_palette": "aap64",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 128,
    },
    "anime": {
        "name": "Anime",
        "tier": "fast",
        "icon": "🌸",
        "prompt_prefix": "anime pixel art, Japanese RPG style, cel-shaded, vibrant colors, JRPG,",
        "negative_extra": "western, realistic, dark, gritty",
        "suggested_palette": "endesga64",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "game_asset": {
        "name": "Game Asset",
        "tier": "fast",
        "icon": "🎮",
        "prompt_prefix": "pixel art game asset, clean sprite, transparent background, game-ready,",
        "negative_extra": "background, scene, landscape, photo",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "portrait": {
        "name": "Portrait",
        "tier": "fast",
        "icon": "🧑",
        "prompt_prefix": "pixel art character portrait, face close-up, RPG dialogue portrait,",
        "negative_extra": "full body, landscape, tiny, far away",
        "suggested_palette": "endesga64",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 96,
    },
    "texture": {
        "name": "Texture",
        "tier": "fast",
        "icon": "🧱",
        "prompt_prefix": "pixel art seamless texture, tileable material, game texture, repeating pattern,",
        "negative_extra": "character, face, object, scene",
        "suggested_palette": "endesga32",
        "suggested_lora": "tileset",
        "suggested_resolution": 64,
    },
    "ui_icon": {
        "name": "UI / Icons",
        "tier": "fast",
        "icon": "🔶",
        "prompt_prefix": "pixel art game icon, clean UI element, game interface icon, small sprite,",
        "negative_extra": "character, landscape, scene, large",
        "suggested_palette": "sweetie16",
        "suggested_lora": "item",
        "suggested_resolution": 32,
    },
    "item_sheet": {
        "name": "Item Sheet",
        "tier": "fast",
        "icon": "📦",
        "prompt_prefix": "pixel art item sprite sheet, multiple items on grid, RPG equipment icons,",
        "negative_extra": "character, landscape, single item, scene",
        "suggested_palette": "endesga32",
        "suggested_lora": "item",
        "suggested_resolution": 32,
    },
    "character_turnaround": {
        "name": "Character Turnaround",
        "tier": "fast",
        "icon": "🔄",
        "prompt_prefix": "pixel art character turnaround, front side back views, character sheet, multiple angles,",
        "negative_extra": "single pose, landscape, scene",
        "suggested_palette": "endesga32",
        "suggested_lora": "character",
        "suggested_resolution": 64,
    },
    "1_bit": {
        "name": "1-Bit",
        "tier": "fast",
        "icon": "⚫",
        "prompt_prefix": "1-bit pixel art, black and white only, monochrome, high contrast, dither pattern,",
        "negative_extra": "color, gradient, gray, anti-aliased",
        "suggested_palette": "1bit",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 64,
    },
    "low_res": {
        "name": "Low Res",
        "tier": "fast",
        "icon": "📐",
        "prompt_prefix": "extremely low resolution pixel art, minimal pixels, 8x8 to 16x16 style, iconic,",
        "negative_extra": "detailed, high resolution, complex, textured",
        "suggested_palette": "pico8",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 16,
    },
    "mc_item": {
        "name": "Minecraft Item",
        "tier": "fast",
        "icon": "⛏️",
        "prompt_prefix": "Minecraft style pixel art item, 16x16 inventory icon, blocky, voxel style,",
        "negative_extra": "round, smooth, detailed, realistic, anti-aliased",
        "suggested_palette": "mc",
        "suggested_lora": "item",
        "suggested_resolution": 16,
    },
    "mc_texture": {
        "name": "Minecraft Texture",
        "tier": "fast",
        "icon": "🟫",
        "prompt_prefix": "Minecraft style seamless texture, 16x16 tileable block texture, voxel material,",
        "negative_extra": "character, object, detailed, high resolution, smooth",
        "suggested_palette": "mc",
        "suggested_lora": "tileset",
        "suggested_resolution": 16,
    },
    "no_style": {
        "name": "No Style",
        "tier": "fast",
        "icon": "🚫",
        "prompt_prefix": "",
        "negative_extra": "",
        "suggested_palette": "",
        "suggested_lora": "none",
        "suggested_resolution": 64,
    },

    # --- PLUS tier: balanced quality/speed ---
    "watercolor": {
        "name": "Watercolor",
        "tier": "plus",
        "icon": "💧",
        "prompt_prefix": "watercolor pixel art, soft washes, paint bleed effect, artistic,",
        "negative_extra": "sharp, digital, clean, mechanical",
        "suggested_palette": "endesga64",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 96,
    },
    "textured": {
        "name": "Textured",
        "tier": "plus",
        "icon": "🪨",
        "prompt_prefix": "textured pixel art, gritty, rough surface detail, organic noise,",
        "negative_extra": "clean, smooth, flat, minimal",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "cartoon": {
        "name": "Cartoon",
        "tier": "plus",
        "icon": "🎪",
        "prompt_prefix": "cartoon pixel art, bold outlines, exaggerated proportions, fun colorful,",
        "negative_extra": "realistic, dark, serious, photographic",
        "suggested_palette": "sweetie16",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "environment": {
        "name": "Environment",
        "tier": "plus",
        "icon": "🌲",
        "prompt_prefix": "pixel art environment, scenic background, game level backdrop, atmospheric,",
        "negative_extra": "character, icon, close-up, UI",
        "suggested_palette": "endesga64",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 256,
    },
    "landscape": {
        "name": "Landscape / Scene",
        "tier": "plus",
        "icon": "🌄",
        "prompt_prefix": "pixel art landscape, scenic wide vista, parallax background, game scene,",
        "negative_extra": "character, icon, close-up, portrait",
        "suggested_palette": "endesga64",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 256,
    },
    "topdown_map": {
        "name": "Top-Down Map",
        "tier": "plus",
        "icon": "🗺️",
        "prompt_prefix": "pixel art top-down map, overworld map, RPG world map, minimap style,",
        "negative_extra": "side view, isometric, character, portrait",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 128,
    },
    "topdown_asset": {
        "name": "Top-Down Asset",
        "tier": "plus",
        "icon": "🏪",
        "prompt_prefix": "pixel art top-down game object, overhead view prop, RPG map decoration,",
        "negative_extra": "side view, isometric, character sprite",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 32,
    },
    "isometric_asset": {
        "name": "Isometric Asset",
        "tier": "plus",
        "icon": "🏗️",
        "prompt_prefix": "isometric pixel art object, 3/4 view prop, isometric game decoration,",
        "negative_extra": "side view, top-down, flat 2D",
        "suggested_palette": "endesga32",
        "suggested_lora": "building",
        "suggested_resolution": 64,
    },
    "classic": {
        "name": "Classic",
        "tier": "plus",
        "icon": "🏛️",
        "prompt_prefix": "classic pixel art, golden age gaming, 90s style, clean pixel work,",
        "negative_extra": "modern, HD, 3D, photo-realistic",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "skill_icon": {
        "name": "Skill Icon",
        "tier": "plus",
        "icon": "✨",
        "prompt_prefix": "pixel art skill icon, ability icon, RPG spell icon, glowing effect,",
        "negative_extra": "character, landscape, scene, large",
        "suggested_palette": "sweetie16",
        "suggested_lora": "item",
        "suggested_resolution": 32,
    },
    "topdown_item": {
        "name": "Top-Down Item",
        "tier": "plus",
        "icon": "💎",
        "prompt_prefix": "pixel art top-down item drop, overhead view pickup, RPG loot sprite,",
        "negative_extra": "side view, character, landscape",
        "suggested_palette": "endesga32",
        "suggested_lora": "item",
        "suggested_resolution": 16,
    },

    # --- CONSOLE-SPECIFIC styles ---
    "gameboy": {
        "name": "Game Boy",
        "tier": "fast",
        "icon": "🟢",
        "prompt_prefix": "Game Boy style pixel art, 4 shades of green, monochrome, retro 8-bit, DMG palette,",
        "negative_extra": "colorful, modern, high resolution, detailed",
        "suggested_palette": "gameboy",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 32,
    },
    "gbc": {
        "name": "Game Boy Color",
        "tier": "fast",
        "icon": "🟣",
        "prompt_prefix": "Game Boy Color pixel art, limited palette, GBC style, handheld retro,",
        "negative_extra": "modern, HD, detailed, realistic",
        "suggested_palette": "sweetie16",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 32,
    },
    "nes_retro": {
        "name": "NES / 8-bit",
        "tier": "fast",
        "icon": "🎮",
        "prompt_prefix": "NES 8-bit pixel art, limited palette, retro Nintendo style, Famicom,",
        "negative_extra": "modern, detailed, high resolution, 16-bit",
        "suggested_palette": "nes",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 32,
    },
    "snes_era": {
        "name": "SNES / 16-bit",
        "tier": "fast",
        "icon": "🕹️",
        "prompt_prefix": "SNES 16-bit pixel art, rich colors, classic Super Nintendo style, Mode 7,",
        "negative_extra": "8-bit, modern, 3D, photo-realistic",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "gba": {
        "name": "GBA",
        "tier": "fast",
        "icon": "🟦",
        "prompt_prefix": "Game Boy Advance pixel art, GBA style, vibrant handheld graphics, 240x160,",
        "negative_extra": "modern, HD, 3D, console quality",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "genesis": {
        "name": "Sega Genesis",
        "tier": "fast",
        "icon": "🔵",
        "prompt_prefix": "Sega Genesis pixel art, Mega Drive style, blast processing, 16-bit Sega,",
        "negative_extra": "8-bit, modern, 3D, Nintendo",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "c64": {
        "name": "Commodore 64",
        "tier": "fast",
        "icon": "🟤",
        "prompt_prefix": "Commodore 64 pixel art, C64 palette, multicolor bitmap, 160x200 style,",
        "negative_extra": "modern, HD, detailed, realistic, many colors",
        "suggested_palette": "c64",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 32,
    },
    "cga": {
        "name": "CGA",
        "tier": "fast",
        "icon": "🟩",
        "prompt_prefix": "CGA pixel art, 4-color palette, IBM PC retro, cyan magenta white black,",
        "negative_extra": "modern, colorful, detailed, realistic",
        "suggested_palette": "cga",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 32,
    },

    # --- CHARACTER STYLES ---
    "chibi": {
        "name": "Chibi / Cute",
        "tier": "plus",
        "icon": "🧸",
        "prompt_prefix": "chibi pixel art, cute deformed style, big head small body, adorable, kawaii,",
        "negative_extra": "realistic, dark, scary, detailed anatomy",
        "suggested_palette": "sweetie16",
        "suggested_lora": "sprite_32",
        "suggested_resolution": 48,
    },
    "warrior": {
        "name": "Warrior / Fighter",
        "tier": "plus",
        "icon": "🗡️",
        "prompt_prefix": "pixel art warrior character, armored fighter, battle-ready, medieval combatant,",
        "negative_extra": "modern, peaceful, cute, sci-fi",
        "suggested_palette": "endesga32",
        "suggested_lora": "character",
        "suggested_resolution": 64,
    },
    "monster": {
        "name": "Monster / Creature",
        "tier": "plus",
        "icon": "👹",
        "prompt_prefix": "pixel art monster, game enemy creature, RPG bestiary, fantasy beast,",
        "negative_extra": "human, cute, modern, realistic",
        "suggested_palette": "endesga32",
        "suggested_lora": "sprite_64",
        "suggested_resolution": 64,
    },
    "npc": {
        "name": "NPC / Townfolk",
        "tier": "plus",
        "icon": "🧑‍🌾",
        "prompt_prefix": "pixel art NPC character, RPG townsperson, friendly villager, game character,",
        "negative_extra": "monster, dark, scary, action",
        "suggested_palette": "endesga32",
        "suggested_lora": "character",
        "suggested_resolution": 48,
    },
}

# =============================================================================
# ANIMATION PRESETS — character actions and VFX
# =============================================================================

ANIMATION_PRESETS = {
    # --- Character walk cycles ---
    "four_angle_walking": {
        "name": "4-Direction Walk",
        "prompt_template": "pixel art character walk cycle sprite sheet, 4 directions (front, back, left, right), 4 frames each, {prompt}",
        "frames": 16,
        "columns": 4,
        "rows": 4,
        "default_size": 48,
        "max_size": 48,
        "type": "character",
    },
    "walking_and_idle": {
        "name": "Walk + Idle",
        "prompt_template": "pixel art character walk and idle sprite sheet, 4 directions walking + idle poses, {prompt}",
        "frames": 20,
        "columns": 4,
        "rows": 5,
        "default_size": 48,
        "max_size": 48,
        "type": "character",
    },
    "small_sprites": {
        "name": "Small Character Set",
        "prompt_template": "tiny pixel art character sprite sheet, walk left right up down, arm wave, look around, surprise, lay down, {prompt}",
        "frames": 24,
        "columns": 6,
        "rows": 4,
        "default_size": 32,
        "max_size": 32,
        "type": "character",
    },

    # --- Advanced character animations ---
    "attack": {
        "name": "Attack",
        "prompt_template": "pixel art attack animation sprite sheet, sword swing slash strike, combat motion, {prompt}",
        "frames_options": [4, 6, 8, 10, 12, 16],
        "default_frames": 6,
        "columns": 4,
        "default_size": 64,
        "max_size": 256,
        "type": "advanced",
        "requires_input": True,
    },
    "idle": {
        "name": "Idle",
        "prompt_template": "pixel art idle animation sprite sheet, subtle breathing movement, standing still, {prompt}",
        "frames_options": [4, 6, 8, 10, 12, 16],
        "default_frames": 4,
        "columns": 4,
        "default_size": 64,
        "max_size": 256,
        "type": "advanced",
        "requires_input": True,
    },
    "walking": {
        "name": "Walking",
        "prompt_template": "pixel art walking animation sprite sheet, walk cycle side view, {prompt}",
        "frames_options": [4, 6, 8, 10, 12, 16],
        "default_frames": 8,
        "columns": 4,
        "default_size": 64,
        "max_size": 256,
        "type": "advanced",
        "requires_input": True,
    },
    "jump": {
        "name": "Jump",
        "prompt_template": "pixel art jump animation sprite sheet, crouch launch airborne land, {prompt}",
        "frames_options": [4, 6, 8, 10, 12, 16],
        "default_frames": 6,
        "columns": 4,
        "default_size": 64,
        "max_size": 256,
        "type": "advanced",
        "requires_input": True,
    },
    "crouch": {
        "name": "Crouch",
        "prompt_template": "pixel art crouch animation sprite sheet, ducking motion, low stance, {prompt}",
        "frames_options": [4, 6, 8, 10, 12, 16],
        "default_frames": 4,
        "columns": 4,
        "default_size": 64,
        "max_size": 256,
        "type": "advanced",
        "requires_input": True,
    },
    "custom_action": {
        "name": "Custom Action",
        "prompt_template": "pixel art animation sprite sheet, {prompt}",
        "frames_options": [4, 6, 8, 10, 12, 16],
        "default_frames": 8,
        "columns": 4,
        "default_size": 64,
        "max_size": 256,
        "type": "advanced",
        "requires_input": True,
    },
    "destroy": {
        "name": "Destroy / Death",
        "prompt_template": "pixel art destruction animation sprite sheet, breaking apart, death sequence, {prompt}",
        "frames_options": [4, 6, 8, 10, 12, 16],
        "default_frames": 8,
        "columns": 4,
        "default_size": 64,
        "max_size": 256,
        "type": "advanced",
        "requires_input": True,
    },
    "subtle_motion": {
        "name": "Subtle Motion",
        "prompt_template": "pixel art subtle motion animation, ambient movement, gentle swaying, {prompt}",
        "frames_options": [4, 6, 8, 10, 12, 16],
        "default_frames": 8,
        "columns": 4,
        "default_size": 64,
        "max_size": 256,
        "type": "advanced",
        "requires_input": False,
    },

    # --- VFX animations ---
    "vfx_fire": {
        "name": "VFX: Fire",
        "prompt_template": "pixel art fire animation sprite sheet, flickering flame loop, campfire, {prompt}",
        "frames": 8,
        "columns": 4,
        "rows": 2,
        "default_size": 48,
        "max_size": 96,
        "type": "vfx",
    },
    "vfx_explosion": {
        "name": "VFX: Explosion",
        "prompt_template": "pixel art explosion animation sprite sheet, blast shockwave debris, {prompt}",
        "frames": 8,
        "columns": 4,
        "rows": 2,
        "default_size": 48,
        "max_size": 96,
        "type": "vfx",
    },
    "vfx_lightning": {
        "name": "VFX: Lightning",
        "prompt_template": "pixel art lightning bolt animation sprite sheet, electric strike, thunder, {prompt}",
        "frames": 6,
        "columns": 3,
        "rows": 2,
        "default_size": 48,
        "max_size": 96,
        "type": "vfx",
    },
    "vfx_smoke": {
        "name": "VFX: Smoke",
        "prompt_template": "pixel art smoke puff animation sprite sheet, dissipating cloud, {prompt}",
        "frames": 8,
        "columns": 4,
        "rows": 2,
        "default_size": 32,
        "max_size": 96,
        "type": "vfx",
    },
    "vfx_magic": {
        "name": "VFX: Magic Spell",
        "prompt_template": "pixel art magic spell effect animation sprite sheet, glowing particles, sparkle, {prompt}",
        "frames": 8,
        "columns": 4,
        "rows": 2,
        "default_size": 48,
        "max_size": 96,
        "type": "vfx",
    },
    "vfx_water": {
        "name": "VFX: Water Splash",
        "prompt_template": "pixel art water splash animation sprite sheet, liquid droplets, ripple, {prompt}",
        "frames": 6,
        "columns": 3,
        "rows": 2,
        "default_size": 32,
        "max_size": 96,
        "type": "vfx",
    },
    "vfx_heal": {
        "name": "VFX: Heal",
        "prompt_template": "pixel art healing effect animation sprite sheet, green sparkles, restoration glow, {prompt}",
        "frames": 8,
        "columns": 4,
        "rows": 2,
        "default_size": 48,
        "max_size": 96,
        "type": "vfx",
    },

    # --- Rotation ---
    "8_dir_rotation": {
        "name": "8-Direction Rotation",
        "prompt_template": "pixel art 8-direction rotation sprite sheet, 8 angles evenly spaced, turntable view, {prompt}",
        "frames": 8,
        "columns": 4,
        "rows": 2,
        "default_size": 80,
        "max_size": 80,
        "type": "rotation",
    },
}

# =============================================================================
# TILESET PRESETS
# =============================================================================

TILESET_PRESETS = {
    "tileset": {
        "name": "Full Wang Tileset",
        "prompt_template": "pixel art wang tileset, complete edge transition tiles, seamless connections, {prompt}",
        "min_size": 16,
        "max_size": 32,
        "default_size": 16,
        "type": "wang",
    },
    "tileset_advanced": {
        "name": "Advanced Two-Texture Tileset",
        "prompt_template": "pixel art two-texture wang tileset, terrain transition tiles between {prompt} and {extra_prompt}",
        "min_size": 16,
        "max_size": 32,
        "default_size": 16,
        "type": "wang_advanced",
        "requires_extra_input": True,
    },
    "single_tile": {
        "name": "Single Tile",
        "prompt_template": "pixel art seamless tileable texture, single repeating tile, {prompt}",
        "min_size": 16,
        "max_size": 64,
        "default_size": 32,
        "type": "single",
    },
    "tile_variation": {
        "name": "Tile Variations",
        "prompt_template": "pixel art tile variations, multiple versions of the same tileable texture, {prompt}",
        "min_size": 16,
        "max_size": 128,
        "default_size": 32,
        "type": "variation",
        "requires_input": True,
    },
    "tile_object": {
        "name": "Tile Object",
        "prompt_template": "pixel art small object for tile map, decoration prop, transparent background, {prompt}",
        "min_size": 16,
        "max_size": 96,
        "default_size": 32,
        "type": "object",
    },
    "scene_object": {
        "name": "Scene Object",
        "prompt_template": "pixel art large scene object, detailed game prop, transparent background, {prompt}",
        "min_size": 64,
        "max_size": 384,
        "default_size": 128,
        "type": "scene",
    },
}

# =============================================================================
# LoRA TRIGGER WORDS & FILE MAPPINGS
# =============================================================================

LORA_TRIGGERS = {
    "sprite_64": "sprites_64, pixel art sprite sheet,",
    "sprite_32": "sprites_32, pixel art sprite sheet,",
    "animal": "animal, pixel art sprite,",
    "weapon": "cold_weapon, pixel art sprite,",
    "gun": "gun, pixel art sprite,",
    "plant": "plant_growth, pixel art sprite,",
    "book": "book, pixel art sprite,",
    "bottle": "bottle, pixel art sprite,",
    "building": "isometry_build, isometric pixel art,",
    "item": "pixel art item sprite,",
    "character": "pixel art character sprite sheet, multiple poses,",
    "tileset": "pixel art tileset, seamless tile,",
    "none": "",
    # Z-Image-Turbo pixel art LoRAs
    "newpixelcore": "pixel art, pixelated,",
    "elusarca": "pixel art, elusarca style,",
}

# Pixel art LoRA filenames
# ComfyUI scans both models/loras/ and D:/AI/Loras/ZIT/ (via extra_model_paths.yaml)
# so multiple names may be available — list all known variants for auto-detection
PIXEL_LORA_VARIANTS = {
    "newpixelcore": [
        "NewPixelCore.safetensors",                                   # local copy
        "NewPixelCore-Z-ImageTurbo_by_VisionaryAI.safetensors",      # ZIT original
    ],
    "elusarca": [
        "elusarcaPixelArt.safetensors",         # local copy
        "elusarca-pixel-art.safetensors",       # ZIT original
    ],
}
# Default filenames (first available will be used at runtime)
ZIT_PIXEL_LORAS = {k: v[0] for k, v in PIXEL_LORA_VARIANTS.items()}

# =============================================================================
# EXPANDED PALETTES — way more than the 7 originals
# =============================================================================

EXTRA_PALETTES = {
    # 1-bit palettes
    "1bit": [(0, 0, 0), (255, 255, 255)],
    "1bit_amber": [(0, 0, 0), (255, 176, 0)],
    "1bit_green": [(0, 0, 0), (0, 255, 65)],

    # CGA palettes
    "cga": [(0, 0, 0), (85, 255, 255), (255, 85, 255), (255, 255, 255)],
    "cga_red": [(0, 0, 0), (85, 255, 85), (255, 85, 85), (255, 255, 85)],

    # Commodore 64
    "c64": [
        (0, 0, 0), (255, 255, 255), (136, 0, 0), (170, 255, 238),
        (204, 68, 204), (0, 204, 85), (0, 0, 170), (238, 238, 119),
        (221, 136, 85), (102, 68, 0), (255, 119, 119), (51, 51, 51),
        (119, 119, 119), (170, 255, 102), (0, 136, 255), (187, 187, 187),
    ],

    # Minecraft-inspired
    "mc": [
        (86, 125, 70), (139, 105, 77), (100, 100, 100), (50, 50, 50),
        (180, 160, 120), (60, 40, 30), (70, 130, 180), (200, 200, 200),
        (170, 50, 50), (40, 80, 40), (140, 140, 60), (100, 60, 30),
        (80, 80, 120), (200, 180, 140), (120, 80, 60), (30, 30, 50),
    ],

    # ZX Spectrum
    "zx": [
        (0, 0, 0), (0, 0, 215), (215, 0, 0), (215, 0, 215),
        (0, 215, 0), (0, 215, 215), (215, 215, 0), (215, 215, 215),
        (0, 0, 255), (255, 0, 0), (255, 0, 255),
        (0, 255, 0), (0, 255, 255), (255, 255, 0), (255, 255, 255),
    ],

    # MSX
    "msx": [
        (0, 0, 0), (1, 1, 1), (62, 184, 73), (116, 208, 125),
        (89, 85, 224), (128, 118, 241), (185, 94, 81), (101, 219, 239),
        (219, 101, 89), (255, 137, 125), (204, 195, 94), (222, 208, 135),
        (58, 162, 65), (183, 102, 181), (204, 204, 204), (255, 255, 255),
    ],

    # Nostalgia
    "nostalgia": [
        (208, 208, 88), (160, 168, 64), (112, 128, 40), (64, 88, 16),
        (216, 176, 112), (184, 136, 80), (136, 96, 48), (88, 56, 16),
        (200, 120, 88), (160, 80, 56), (120, 48, 32), (80, 24, 16),
        (168, 168, 168), (120, 120, 120), (72, 72, 72), (24, 24, 24),
    ],

    # Resurrect 64 (popular pixel art palette)
    "resurrect64": [
        (46, 34, 47), (62, 53, 70), (80, 73, 95), (101, 97, 115),
        (146, 143, 151), (198, 195, 198), (226, 226, 219), (245, 243, 240),
        (255, 166, 119), (255, 130, 73), (211, 95, 63), (163, 64, 53),
        (119, 41, 44), (87, 28, 39), (55, 22, 36), (34, 15, 30),
        (194, 185, 121), (162, 162, 80), (121, 141, 59), (79, 121, 66),
        (46, 99, 74), (28, 74, 81), (22, 50, 74), (25, 32, 52),
        (64, 128, 168), (107, 162, 195), (157, 199, 207), (194, 228, 216),
        (243, 200, 163), (229, 171, 125), (191, 128, 97), (153, 97, 80),
        (255, 210, 63), (245, 169, 59), (220, 125, 72), (190, 90, 63),
        (196, 79, 119), (165, 55, 109), (118, 40, 93), (73, 36, 79),
        (107, 172, 172), (82, 139, 141), (55, 103, 113), (36, 70, 89),
        (36, 36, 55), (58, 48, 66), (84, 64, 76), (116, 87, 85),
        (157, 116, 96), (191, 149, 116), (211, 177, 143), (236, 210, 178),
        (255, 234, 195), (255, 247, 221), (239, 216, 191), (211, 186, 168),
        (179, 153, 146), (145, 124, 124), (115, 99, 102), (89, 77, 82),
        (61, 57, 63), (42, 39, 49), (30, 27, 36), (17, 14, 22),
    ],

    # APOLLO
    "apollo": [
        (23, 14, 22), (38, 31, 41), (46, 46, 64), (57, 67, 86),
        (79, 96, 110), (106, 128, 130), (145, 166, 151), (181, 199, 170),
        (220, 229, 199), (147, 105, 78), (119, 72, 54), (94, 47, 40),
        (68, 32, 32), (43, 22, 27), (115, 41, 48), (167, 60, 63),
        (202, 98, 72), (222, 142, 81), (239, 185, 100), (246, 226, 144),
        (209, 155, 128), (179, 113, 105), (151, 78, 90), (116, 51, 75),
        (75, 37, 67), (49, 29, 52), (36, 42, 79), (53, 70, 115),
        (79, 107, 152), (110, 148, 183), (155, 190, 205), (199, 224, 222),
        (81, 102, 68), (63, 73, 47), (47, 50, 34), (35, 32, 26),
    ],

    # STEAM LORDS
    "steamlords": [
        (33, 30, 51), (46, 53, 77), (62, 79, 92), (92, 108, 93),
        (143, 151, 117), (194, 195, 148), (219, 214, 167), (238, 235, 195),
        (84, 51, 68), (127, 72, 75), (171, 104, 78), (207, 144, 85),
        (230, 187, 106), (243, 222, 138), (255, 250, 172), (255, 255, 215),
    ],

    # JOURNEY
    "journey": [
        (5, 5, 15), (18, 18, 36), (36, 36, 56), (58, 60, 83),
        (82, 89, 113), (117, 125, 143), (164, 170, 182), (218, 224, 234),
        (254, 254, 254), (190, 119, 43), (245, 179, 66), (255, 235, 148),
        (255, 248, 207), (162, 59, 55), (216, 91, 80), (251, 147, 102),
        (248, 200, 158), (46, 56, 88), (57, 85, 119), (77, 125, 153),
        (109, 172, 186), (158, 215, 213), (189, 232, 223), (42, 69, 61),
        (56, 100, 76), (80, 141, 94), (130, 182, 115), (185, 214, 144),
        (217, 235, 180), (102, 42, 67), (143, 57, 93), (186, 80, 117),
        (221, 128, 156), (241, 179, 191), (253, 217, 219),
    ],
}

# =============================================================================
# RESOLUTION + MISC CONFIG
# =============================================================================

PIXEL_RESOLUTIONS = [8, 16, 24, 32, 48, 64, 80, 96, 128, 192, 256, 384, 512]

# Upscale factors for pixel-perfect nearest-neighbor scaling
UPSCALE_FACTORS = [1, 2, 3, 4, 6, 8, 10, 16]

# Valid frame durations for advanced animations
FRAME_DURATION_OPTIONS = [4, 6, 8, 10, 12, 16]

# Output format options
OUTPUT_FORMATS = ["png", "gif", "spritesheet", "apng"]
